/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import DAO.CitoyenDAO;
import DAO.EtablissementDAO;
import DAO.ReclamationDAO;
import Entities.Citoyen;
import Entities.Etablissement;
import Entities.Reclamation;
import java.util.ArrayList;

import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;


/**
 *
 * @author abrar
 */
public class ADD_Reclamation extends javax.swing.JFrame {

    /**
     * Creates new form ADD_Reclamation
     */
    public ADD_Reclamation() {
        initComponents();
         EtablissementDAO E = new EtablissementDAO();
        List<Etablissement> L = new ArrayList<Etablissement>();//créer une liste de depot car DisplayAllDepot retourne une liste de depot 
       L = E.DisplayAllEtablissement();//
        for(Etablissement Etab :L)//en suite pour chaque objet de la liste ,on l'ajoute dans le combobox
        {
            jComboBoxEtab.addItem(Etab.getName());//+" "+Etab.getGouvernerat()+" "+Etab.getVille());//pour remplir le combobox de l'adresse du depot avec les adresse des depot à partir de la table depot 
          // jComboBoxVille.addItem(Etab.getVille());
          // jComboBoxGouver.addItem(Etab.getGouvernerat());
        }
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaText = new javax.swing.JTextArea();
        jTextFieldSujet = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonInfo = new javax.swing.JRadioButton();
        jRadioButtonFraude = new javax.swing.JRadioButton();
        jButtonAjouter = new javax.swing.JButton();
        jComboBoxEtab = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sujet:");

        jTextAreaText.setColumns(20);
        jTextAreaText.setRows(5);
        jScrollPane1.setViewportView(jTextAreaText);

        jTextFieldSujet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSujetActionPerformed(evt);
            }
        });

        jLabel2.setText("Type réclamation:");

        buttonGroup1.add(jRadioButtonInfo);
        jRadioButtonInfo.setText("Information");
        jRadioButtonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonInfoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonFraude);
        jRadioButtonFraude.setText("Signaler un fraude");
        jRadioButtonFraude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFraudeActionPerformed(evt);
            }
        });

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jComboBoxEtab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEtabActionPerformed(evt);
            }
        });

        jLabel3.setText("établissement concernée:");

        jLabel4.setText("Réclamation ajouté par(Login):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonInfo)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonFraude))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAjouter)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxEtab, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldSujet)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(594, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRadioButtonInfo)
                    .addComponent(jRadioButtonFraude))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxEtab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSujet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAjouter)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSujetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSujetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSujetActionPerformed
   
    private void jRadioButtonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonInfoActionPerformed

    private void jRadioButtonFraudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFraudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFraudeActionPerformed

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        // TODO add your handling code here:
        String Type;
        String Login = jTextFieldLogin.getText();
        String Sujet =jTextFieldSujet.getText();
        String Etabnom = (String)jComboBoxEtab.getSelectedItem();
         String Text= jTextAreaText.getText();
       
         CitoyenDAO C = new CitoyenDAO();
         Citoyen cit= new Citoyen();
         cit=C.findCitoyentByLogin(Login);
         if(cit!=null)
         {
             Reclamation R = new Reclamation();
             R.setEtat("Non traité");
             R.setDegreUrgence(0);
             R.setSujet(Sujet);
             java.util.GregorianCalendar calendar = new GregorianCalendar();
				java.util.Date time  = calendar.getTime();
				         //System.out.println(time);
              
            // java.util.Date date = new java.util.Date(); 
 

            R.setDateReclamation((time) );
             R.setIdCitoyen(cit);
           // R.setResponsableIdResponsable(null);
            R.settext(Text);
             if(jRadioButtonFraude.isSelected())
         { Type=jRadioButtonFraude.getText();
         R.settype(Type);
         }
         else if (jRadioButtonInfo.isSelected())
         {Type=jRadioButtonInfo.getText();
         R.settype(Type);
         }
             EtablissementDAO EtabDAO= new EtablissementDAO();
             R.setetbalissement_id_etablissement(EtabDAO.findEtablissementtByName(Etabnom));
            ReclamationDAO Re = new ReclamationDAO();
            Re.insertReclamation(R);
             
         }
         
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jComboBoxEtabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEtabActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxEtabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADD_Reclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADD_Reclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADD_Reclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADD_Reclamation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADD_Reclamation().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JComboBox jComboBoxEtab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButtonFraude;
    private javax.swing.JRadioButton jRadioButtonInfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaText;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldSujet;
    // End of variables declaration//GEN-END:variables
}
